package entities;
// Generated Mar 16, 2018 11:21:56 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SalaryGrade generated by hbm2java
 */
@Entity
@Table(name = "SALARY_GRADE", schema = "dbo", catalog = "staffmanager")
public class SalaryGrade implements java.io.Serializable {

	private int grade;
	private double highSalary;
	private double lowSalary;

	public SalaryGrade() {
	}

	public SalaryGrade(int grade, double highSalary, double lowSalary) {
		this.grade = grade;
		this.highSalary = highSalary;
		this.lowSalary = lowSalary;
	}

	@Id

	@Column(name = "GRADE", unique = true, nullable = false)
	public int getGrade() {
		return this.grade;
	}

	public void setGrade(int grade) {
		this.grade = grade;
	}

	@Column(name = "HIGH_SALARY", nullable = false, precision = 53, scale = 0)
	public double getHighSalary() {
		return this.highSalary;
	}

	public void setHighSalary(double highSalary) {
		this.highSalary = highSalary;
	}

	@Column(name = "LOW_SALARY", nullable = false, precision = 53, scale = 0)
	public double getLowSalary() {
		return this.lowSalary;
	}

	public void setLowSalary(double lowSalary) {
		this.lowSalary = lowSalary;
	}

}
