package entities;
// Generated Mar 16, 2018 11:21:56 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Timekeeper generated by hbm2java
 */
@Entity
@Table(name = "TIMEKEEPER", schema = "dbo", catalog = "staffmanager")
public class Timekeeper implements java.io.Serializable {

	private String timekeeperId;
	private Employee employee;
	private Date dateTime;
	private char inOut;

	public Timekeeper() {
	}

	public Timekeeper(String timekeeperId, Employee employee, Date dateTime, char inOut) {
		this.timekeeperId = timekeeperId;
		this.employee = employee;
		this.dateTime = dateTime;
		this.inOut = inOut;
	}

	@Id

	@Column(name = "Timekeeper_Id", unique = true, nullable = false, length = 36)
	public String getTimekeeperId() {
		return this.timekeeperId;
	}

	public void setTimekeeperId(String timekeeperId) {
		this.timekeeperId = timekeeperId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMP_ID", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date_Time", nullable = false, length = 23)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "In_Out", nullable = false, length = 1)
	public char getInOut() {
		return this.inOut;
	}

	public void setInOut(char inOut) {
		this.inOut = inOut;
	}

}
